version: "3"
services:
  app:
    image: swift
    volumes:
      - .:/app
    working_dir: /app
    # needed for REPL begin
    cap_add:
      - sys_ptrace
    privileged: true
    # needed for REPL end

